[build]
  base = "./frontend/"
  command = "npm run build" # ou o comando principal para o monorepo
  publish = "/dist" # caminho para o front-end gerado

[functions]
    directory = "../backend/functions"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
