[build]
  command = "npm run build" # ou o comando principal para o monorepo
  publish = "/dist" # caminho para o front-end gerado
  functions = "../backend/functions" # onde estão as funções do back-end

