[build]
  base = "./frontend/"
  command = "npm run build" # ou o comando principal para o monorepo
  publish = "/dist" # caminho para o front-end gerado

[functions]
    directory = "../backend/api"
