# .gitlab-ci.yml

stages:
  - install
  - build
  - deploy

variables:
  NODE_ENV: 'production'
  CACHE_DIR: '.cache'

# Global include for the SAST scan
include:
  - template: Security/SAST.gitlab-ci.yml

# Install dependencies (frontend and backend)
install_dependencies:
  stage: install
  image: node:16
  script:
    - cd frontend && npm ci
    - cd ../backend && npm ci
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - frontend/node_modules
      - backend/node_modules

# Security SAST scan
sast:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop"

# Build frontend and backend
build:
  stage: build
  image: node:16
  script:
    - cd frontend && npm run build
    - cd ../backend && npm run build
  artifacts:
    paths:
      - frontend/dist
      - backend/dist

# Deploy the project
deploy:
  stage: deploy
  image: ruby:3.1
  script:
    - echo "Deploying the project..."
    # Add your deployment commands here, e.g., SSH to server or upload artifacts.
  only:
    - main
  environment:
    name: production
