# .gitlab-ci.yml

stages:
  - install
  - test
  - build
  - deploy

variables:
  NODE_ENV: 'production'
  CACHE_DIR: '.cache'

# Install dependencies (frontend and backend)
install_dependencies:
  stage: install
  script:
    - cd frontend && npm ci
    - cd ../backend && npm ci
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - frontend/node_modules
      - backend/node_modules

# Run unit tests
test:
  stage: test
  script:
    - cd frontend && npm test
    - cd ../backend && npm run test

# Security SAST scan
sast:
  stage: test
  include:
    - template: Security/SAST.gitlab-ci.yml
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop"

# Build frontend and backend
build:
  stage: build
  script:
    - cd frontend && npm run build
    - cd ../backend && npm run build
  artifacts:
    paths:
      - frontend/dist
      - backend/dist

# Deploy the project
deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
    # Add your deployment commands here, e.g., SSH to server or upload artifacts.
  only:
    - main
  environment:
    name: production
