[build]
  command = "npm run build"
  publish = "frontend/dist"

[functions]
  directory = "backend/functions"
  node_bundler = "esbuild"
  external_node_modules = ["crypto-browserify"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://your-frontend-domain.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"



