[build]
  command = "npm run build"
  publish = "frontend/dist"

[functions]
  directory = "backend/functions"
  node_bundler = "esbuild"
  external_node_modules = ["crypto-browserify"]

# Redireciona todas as chamadas de API para a função api
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redireciona chamadas específicas para a mesma função
[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/api/auth/:splat"
  status = 200

[[redirects]]
  from = "/users/*"
  to = "/.netlify/functions/api/users/:splat"
  status = 200

[[redirects]]
  from = "/stories/*"
  to = "/.netlify/functions/api/stories/:splat"
  status = 200

[[redirects]]
  from = "/ai/*"
  to = "/.netlify/functions/api/ai/:splat"
  status = 200

# Redireciona todas as outras rotas para o frontend
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"



