[build]
  command = "npm run build"
  publish = "frontend/dist"

[functions]
  directory = "backend/functions"
  node_bundler = "esbuild"
  external_node_modules = ["crypto-browserify"]
  included_files = ["services/notificationService.js", "config/database.js", "utils/logger.js"]

[functions."*"]  # Applies to all functions
  timeout = 30
  
[functions.scheduleNotifyInactiveUsers]
  schedule = "0 0 * * *"

# Redirecionar rotas específicas
[[redirects]]
  from = "/api/users/login"
  to = "/.netlify/functions/users/login"
  status = 200
  force = true

[[redirects]]
  from = "/api/users/*"
  to = "/.netlify/functions/users/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Global headers
[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
      Access-Control-Allow-Headers = "Content-Type, Authorization"
      Access-Control-Allow-Credentials = "true"

# Dev-specific settings
[dev]
  port = 8888
  publish = "frontend/dist"

